const departments = [
  'AMAZONAS',
  'ANTIOQUIA',
  'ARAUCA',
  'ATLÁNTICO',
  'BOGOTÁ D.C.',
  'BOLÍVAR',
  'BOYACÁ',
  'CALDAS',
  'CAQUETÁ',
  'CASANARE',
  'CAUCA',
  'CESAR',
  'CHOCÓ',
  'CÓRDOBA',
  'CUNDINAMARCA',
  'GUAINÍA',
  'GUAVIARE',
  'HUILA',
  'LA GUAJIRA',
  'MAGDALENA',
  'META',
  'NARIÑO',
  'NORTE DE SANTANDER',
  'PUTUMAYO',
  'QUINDÍO',
  'RISARALDA',
  'SAN ANDRÉS Y PROVIDENCIA',
  'SANTA CATALINA',
  'SANTANDER',
  'SUCRE',
  'TOLIMA',
  'VALLE DEL CAUCA',
  'VAUPÉS',
  'VICHADA',
];

export default departments;
